### ISSUE TITLE
Removal Reasons not working properly?

### ISSUE THREAD

**Issue by ICantThinkOfNameHelp** [garretyoder/ModSoup#1]
So, I have removal reasons enabled but the removal reasons are only working for 1 subreddit I moderate. Every subreddit I moderate uses toolbox.

Here are some screenshots:

http://i.imgur.com/FGO4ckL.png

http://i.imgur.com/piyJmDR.png

**Comment by garretyoder** [comment]
Can you grab me a logcat? Modsoup will log exactly why the reasons aren't fetching to the log of your phone.

**Comment by ICantThinkOfNameHelp** [comment]
What are some practical ways to access it?

**Comment by garretyoder** [comment]
I pushed a update recently that most likely fixed this issue. Verify that it's fixed?

**Comment by ICantThinkOfNameHelp** [comment]
Yup, it's fixed. Also, sorry for not replying for so long :(

**Comment by ICantThinkOfNameHelp** [comment]
Thank you!

**Comment by dubyadud** [comment]
The removal reasons still disappear on occasion
